/* tslint:disable */
/* eslint-disable */
/**
 * Catalog - OpenAPI 3.0
 * This is a sample Catalog microservice based on the OpenAPI 3.0 specification.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: filario@redhat.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

