Parameters:
  LambdaName:
      Description: Name of Lambda function managing DynamoDB stream events
      Type: String
      MinLength: '1'
      MaxLength: '16'
  QueueURL:
      Description: URL of the queue that will receive the DynamoDB stream events
      Type: String
      MinLength: '1'
      MaxLength: '100'
Resources:
  eventrouterServiceRoleBA1488D7:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
        Version: 2012-10-17
      ManagedPolicyArns:
        - !Join 
          - ''
          - - 'arn:'
            - !Ref 'AWS::Partition'
            - ':iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
  eventrouterServiceRoleDefaultPolicy847DED66:
    Type: 'AWS::IAM::Policy'
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - 'dynamodb:ListStreams'
              - 'sqs:SendMessage'
            Effect: Allow
            Resource: '*'
          - Action:
              - 'dynamodb:DescribeStream'
              - 'dynamodb:GetRecords'
              - 'dynamodb:GetShardIterator'
            Effect: Allow
            Resource: !GetAtt 
              - OrdersA9B65338
              - StreamArn
        Version: 2012-10-17
      PolicyName: eventrouterServiceRoleDefaultPolicy847DED66
      Roles:
        - !Ref eventrouterServiceRoleBA1488D7
  eventrouter92364A2D:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket: !Sub 'cdk-hnb659fds-assets-${AWS::AccountId}-${AWS::Region}'
        S3Key: 01ccc5e1ebb473ae27557ebe91ff1ea9c6fedb72cbe8a467095d33892419781c.zip
      Role: !GetAtt 
        - eventrouterServiceRoleBA1488D7
        - Arn
      Architectures:
        - x86_64
      Description: Application Event Router
      Environment:
        Variables:
          TARGET_QUEUE: !Ref QueueURL
      FunctionName: !Ref LambdaName
      Handler: event_router.handler
      MemorySize: 1024
      Runtime: python3.10
      Timeout: 300
    DependsOn:
      - eventrouterServiceRoleDefaultPolicy847DED66
      - eventrouterServiceRoleBA1488D7
  eventrouterDynamoDBEventSourceprimazadynamoOrdersC5583D99833229C7:
    Type: 'AWS::Lambda::EventSourceMapping'
    Properties:
      FunctionName: !Ref eventrouter92364A2D
      BatchSize: 100
      EventSourceArn: !GetAtt 
        - OrdersA9B65338
        - StreamArn
      StartingPosition: LATEST
  OrdersA9B65338:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      KeySchema:
        - AttributeName: ID
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: ID
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      StreamSpecification:
        StreamViewType: NEW_IMAGE
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
Outputs:
  TableName:
    Description: DynamoDB table name
    Value: !Ref OrdersA9B65338
  Region:
    Description: AWS Region
    Value: !Ref "AWS::Region"
  AccessKeyRef:
    Description: Reference to Access Key in SecretsManager
    Value: "demo_access_key"
  SecretKeyRef:
    Description: Reference to Secret Key in SecretsManager
    Value: "demo_secret_key"  
  type:
    Description: type of service
    Value: dynamodb
